export const WeekDays = {
  Sat: "Sat",
  Mon: "Mon",
  Tue: "Tue",
  Wed: "Wed",
  Thu: "Thu",
  Fri: "Fri",
  Sun: "Sun",
};

export const NewOffice = {
  officeId: null,
  street: "",
  unit: "",
  city: "",
  state: "",
  zip: "",
  phone: "",
  fax: "",
  email: "",
  acceptingWalkIns: false,
  mapUrl: "",
  introduction: "",
  officeSocialMedialProfile: {
    linkedin: "",
    youtube: "",
    facebook: "",
    myspace: "",
    instagram: "",
    yelp: "",
    tiktok: "",
    x: "",
    pinterest: "",
    snapchat: "",
    whatsapp: "",
    tumblr: "",
    google: "",
    id: null,
  },
  schedule: [
    { id: null, day: WeekDays.Mon, beginTime: "07:00:00", endTime: "18:30:00" },
    { id: null, day: WeekDays.Wed, beginTime: "07:00:00", endTime: "18:30:00" },
    { id: null, day: WeekDays.Thu, beginTime: "07:00:00", endTime: "18:30:00" },
    { id: null, day: WeekDays.Fri, beginTime: "13:00:00", endTime: "15:00:00" },
    { id: null, day: WeekDays.Tue, beginTime: "07:00:00", endTime: "18:30:00" },
  ],
  employees: [],
};
